### ISSUE TITLE
[Bug] Key presses registererd multiple times after focus loss

### ISSUE THREAD

**Issue by short-circuit** [hyprwm/hyprlock#66] opened 2024-02-22 21:15 UTC
Whenever I lock my screen and unlock it immediately, Hyprlock works as intended.
As soon as the locksreen looses focus (tty change, suspend and resume), it becomes impossible to login again.
The problem is, that each key press is registered multiple times, with a multiplication factor of how many time the lock screen lost focus (e.g. if I change to tty3 4 times, it will register each keypress 4 times + 1 original press)

How can I provide logs? Hyprlock currently only logs unsuccessful attempts and nothing else. 

EDIT:
Currently changed back to swaylock and it works perfectly. So definitely a bug in hyprlock. 
Please let me know how to correctly provide logs, because I really like hyprlock and I want to help

**Comment by vaxerski** [comment] 2024-02-22 21:51
logs go to stdout

**Comment by Poly-cryptic** [comment] 2024-02-23 03:13
> hyprlock -v > log.txt

**Comment by tchofy** [comment] 2024-02-23 05:18
Can reproduce it as well, but mine is always 2 extra characters for every tty swap, happens on suspend as well.

Here's the log, and for recerence I did was:
```
hyprlock -v > log.txt
switch tty and wait a couple seconds
switch back to hyprland
type password (3 characters for every keypress, the key I'm pressing and 2 extra characters for every tty change)
press enter
authentication fails
switch again to tty
kill hyprlock
```
[log.txt](https://github.com/hyprwm/hyprlock/files/14381891/log.txt)

**Comment by vaxerski** [comment] 2024-02-25 19:01
[patch69.txt](https://github.com/hyprwm/hyprlock/files/14397482/patch69.txt)
can someone give me a `-v` log with this patch

Also please dont type your actual password, this will log all key down and up events, I want to see if I can filter the duplicates somehow.

Type something like "abcdefg" or "penis" while the bug is happening

**Comment by n-ameless** [comment] 2024-02-25 21:26
[log.txt](https://github.com/hyprwm/hyprlock/files/14397895/log.txt)

My log after typing "penispenis"

**Comment by vaxerski** [comment] 2024-02-25 22:50
ok yeah should be easily fixable

**Comment by vaxerski** [comment] 2024-02-25 22:54
[patch69.txt](https://github.com/hyprwm/hyprlock/files/14398147/patch69.txt)
should fix

**Comment by n-ameless** [comment] 2024-02-26 00:03
> [patch69.txt](https://github.com/hyprwm/hyprlock/files/14398147/patch69.txt)
> should fix

Issue persists on my machine.

**Comment by vaxerski** [comment] 2024-02-26 00:29
not possible

**Comment by vaxerski** [comment] 2024-02-26 00:30
[patch69.txt](https://github.com/hyprwm/hyprlock/files/14398399/patch69.txt)
ah no nvm definitely possible if I am an idiot. Fixed.

**Comment by n-ameless** [comment] 2024-02-26 00:54
Issue _still_ persists, this time its only one extra keystroke (two inputs per keystroke).

**Comment by vaxerski** [comment] 2024-02-26 01:44
[patch69.txt](https://github.com/hyprwm/hyprlock/files/14398737/patch69.txt)
sorry my mental retardation is shining through

**Comment by n-ameless** [comment] 2024-02-26 02:24
> [patch69.txt](https://github.com/hyprwm/hyprlock/files/14398737/patch69.txt) sorry my mental retardation is shining through

Seems like its fixed now :) After three attempts I cannot reproduce the bug anymore. Highly appreciated.

**Closed** 2024-02-26 02:28 UTC

**Comment by n-ameless** [comment] 2024-02-26 03:27
Just noticed that this patch introduces a new bug where hyprlock treats some valid inputs as invalid key events, which will occasionally make my submitted password incorrect. This can be observed when repeating SHIFT + Letter inputs. It also adds a noticeable input delay.

**Comment by vaxerski** [comment] 2024-02-26 03:28
open a new issue
