### ISSUE TITLE
`$TIME` label doesn't update

### ISSUE THREAD

**Issue by ThinkChaos** [hyprwm/hyprlock#390] opened 2024-07-01 14:24 UTC
When leaving hyprlock running for a while, `$TIME` stops updating. It seems to stop a couple minutes after locking, and re-updates itself a bit after user input.
I noticed that a `cmd` label does update, so with the config below, the cmd date is on time while `$TIME` stops updating. So it seems to be `$TIME` specific (or maybe any label without `cmd[update]`).

I was hoping this would be resolved at the same time as #357, but I still have the issue even with 318c00d6d093d6d0da2687ad51880578a49899dd.
Just in case, I have dual screens and an AMD GPU.

<details>

<summary>config</summary>

```
label {
  monitor=DP-1
  font_family=monospace
  font_size=150
  text=$TIME
  text_align=center
}

label {
  monitor=DP-1
  font_family=monospace
  font_size=150
  halign=center
  text=cmd[update:1000] date
  text_align=center
  valign=center
}
```
</details>

**Comment by PaideiaDilemma** [comment] 2024-07-01 15:19
Hmm can you check if `Trying to update label, but resource {} is still pending! Skipping update.` is in the logs when it happens?
I will see if I can reproduce it.

**Comment by PaideiaDilemma** [comment] 2024-07-03 15:03
Does not happen on my side. Also AMD GPU and multi monitor. I think the fact that `$TIME` is used does not matter. To be honest i don't understand how that can happen after https://github.com/hyprwm/hyprlock/commit/318c00d6d093d6d0da2687ad51880578a49899dd

**Comment by ThinkChaos** [comment] 2024-07-04 01:57
Indeed that log appears. Here's my service's log, with artificial paragraphs to highlight the pattern.
Note that this was generated from a slightly different config than posted above since it's from my actual setup.

```
Jul 03 18:09:00 Workstation hyprlock[1537280]: [LOG] Configuring surface for logical [Vector2D: x: 3840, y: 2160] and pixel [Vector2D: x: 3840, y: 2160]
Jul 03 18:09:00 Workstation hyprlock[1537280]: [ERR] Unknown prop in string format
Jul 03 18:09:00 Workstation hyprlock[1537280]: [LOG] got fractional 1
Jul 03 18:09:00 Workstation hyprlock[1537280]: [LOG] configure with serial 176420
Jul 03 18:09:00 Workstation hyprlock[1537280]: [LOG] Configuring surface for logical [Vector2D: x: 1920, y: 1080] and pixel [Vector2D: x: 1920, y: 1080]
Jul 03 18:09:00 Workstation hyprlock[1537280]: [LOG] Framebuffer created, status 36053
Jul 03 18:09:00 Workstation hyprlock[1537280]: [LOG] Framebuffer created, status 36053
Jul 03 18:09:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:09:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:09:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:09:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:09:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:09:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:09:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:09:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:09:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:09:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:09:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:09:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:09:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:09:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:09:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:09:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:09:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:09:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:09:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:09:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:09:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:09:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:09:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:09:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:09:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:09:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:09:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:09:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:09:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:09:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:09:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:43:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:43:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:43:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:43:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:43:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:43:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:43:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:43:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:43:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:43:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:43:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:43:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:43:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:43:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:43:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:43:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:43:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:43:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:43:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:43:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:43:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:43:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:43:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:43:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:43:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:43:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:43:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:43:00 Workstation hyprlock[1537280]: [ERR] Unknown prop in string format
Jul 03 18:43:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:43:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:43:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:43:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:43:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:43:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 18:43:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
Jul 03 19:18:00 Workstation hyprlock[1537280]: [WARN] Trying to update label, but resource label:18139536,time:1720042620984795395 is still pending! Skipping update.
```

**Comment by PaideiaDilemma** [comment] 2024-07-04 18:51
Can you send the exact labels you are using?

**Comment by ilolm** [comment] 2024-07-10 07:17
Actually  318c00d didn't fix my issue

**Comment by PaideiaDilemma** [comment] 2024-07-10 09:29
@ilolm I think you are on nvidia right? Sorry for closing your issue (#357) with the MR.
It should have actually been marked as a duplicate of #249.

 @ThinkChaos because of the `[ERR] Unknown prop in string format[ERR] Unknown prop in string format` log, I kinda wonder about your specific label configuration.

**Comment by PaideiaDilemma** [comment] 2024-07-10 14:28
@ThinkChaos I added some trace logs in e5f0b56d07f13db6a4542ff5fa5a3e31e61169bc.
It would be very helpful, if you could update and try to reproduce the problem with `hyprlock --verbose`.
That will produce quite a lot of logs, but they would help to fix this :)

**Comment by ThinkChaos** [comment] 2024-07-10 16:17
Sorry I haven't been very responsive, I'm not able to spend much time on the computer for health reasons.
I ran that commit with the minimal config above in verbose mode. Just locked, waited a bit and unlocked. Let me know if you want the output of a longer run where I notice it's out of date.
Here's the output: [hyprlock.service log](https://github.com/user-attachments/files/16165044/h.log) (via attachment since there's to much data to post inline).

Here's my real config (I know some things are redundant with defaults, it's because it's generated via Nix where I have variables):
```
background {
  monitor=DP-1
  blur_passes=3
  blur_size=10
  path=screenshot
}

background {
  monitor=DP-2
  color=rgb(0, 0, 0)
}

general {
  hide_cursor=true
  ignore_empty_input=true
  no_fade_in=true
  no_fade_out=false
}

input-field {
  monitor=DP-1
  size=200, 25
  check_color=rgb(204, 136, 34)
  fade_on_empty=true
  fade_timeout=5000
  fail_color=rgb(204, 34, 34)
  fail_text=
  fail_transition=300
  font_color=rgb(200, 200, 200)
  halign=center
  inner_color=rgb(10, 10, 10)
  outer_color=rgb(15, 15, 15)
  outline_thickness=2
  placeholder_text=
  position=0, 0
  shadow_passes=3
  shadow_size=5
  valign=center
}

label {
  monitor=DP-1
  font_family=monospace
  font_size=150
  halign=center
  position=0, 540
  shadow_boost=2
  shadow_passes=3
  shadow_size=10
  text=$TIME
  text_align=center
  valign=center
}

label {
  monitor=DP-1
  color=rgb(204, 34, 34)
  font_size=15
  halign=center
  position=0, 405
  text=cmd[] if [ $ATTEMPTS -ne 0 ]; then echo '$FAIL ($ATTEMPTS)'; fi
  text_align=center
  valign=center
}
```

Maybe the unknown prop error is because of `cmd[]` (without `update:`)? Only guessing based on the message.

**Closed** 2024-07-24 21:18 UTC

**Comment by PaideiaDilemma** [comment] 2024-07-25 09:05
Hi @ThinkChaos. Hope you are well.

Can you check if this is resolved for you?
I am pretty sure that the last PR should ensure it updates, even if a label update was missed for some reason. Thanks!

**Comment by ThinkChaos** [comment] 2024-07-26 02:42
Looks like it did the trick!  
Thanks!
