### ISSUE TITLE
Total (reproducible) crash when monitor power cycles

### ISSUE THREAD

**Issue by djvs** [hyprwm/hyprlock#476] opened 2024-09-03 12:52 UTC
### Regression?

No

### Hyprlock Info and Version

hyprlock 0.4.1-1 (arch/artix)

<details> <summary>Hyprlock config</summary>

```sh
background {
    monitor =
    # path = /home/me/someImage.png   # only png supported for now
    path = /ignorethis.png
    color = rgba(25, 205, 20, 1.0)

    # all these options are taken from hyprland, see https://wiki.hyprland.org/Configuring/Variables/#blur for explanations
    blur_passes = 0 # 0 disables blurring
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 200, 50
    outline_thickness = 3
    dots_size = 0.33 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.15 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = false
    dots_rounding = -1 # -1 default circle, -2 follow input-field rounding
    outer_color = rgb(151515)
    inner_color = rgb(255, 255, 255)
    font_color = rgb(10, 10, 10)
    fade_on_empty = false
    fade_timeout = 1000 # Milliseconds before fade_on_empty is triggered.
    placeholder_text = <i>Input Password...</i> # Text rendered in the input box when it's empty.
    hide_input = false
    rounding = -1 # -1 means complete rounding (circle/oval)
    check_color = rgb(204, 136, 34)
    fail_color = rgb(204, 34, 34) # if authentication failed, changes outer_color and fail message color
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i> # can be set to empty
    fail_transition = 300 # transition time in ms between normal outer_color and fail_color
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1 # when both locks are active. -1 means don't change outer color (same for above)
    invert_numlock = false # change color if numlock is off
    swap_font_color = false # see below

    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = sign in $USER
    #color = rgba(200, 200, 200, 1.0)
    color = rgba(255, 255, 255, 1.0)
    font_size = 25
    font_family = Noto Sans
    rotate = 0 # degrees, counter-clockwise

    position = 0, 80
    halign = center
    valign = center
}
```

</details>

### Compositor Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 9a09eac79b85c846e3a865a9078a3f8ff65a9259  (props: bump version to 0.42.0).
Date: Wed Aug 7 19:17:10 2024
Tag: v0.42.0, commits: 5069

flags: (if any)


System Information:
System name: Linux
Node name: blu
Release: 6.10.6-artix1-1
Version: #1 SMP PREEMPT_DYNAMIC Tue, 20 Aug 2024 02:43:37 +0000


GPU information: 
2d:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT] [1002:73df] (rev c1) (prog-if 00 [VGA controller])


os-release: NAME="Artix Linux"
PRETTY_NAME="Artix Linux"
ID=artix
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.artixlinux.org/"
DOCUMENTATION_URL="https://wiki.artixlinux.org/"
SUPPORT_URL="https://forum.artixlinux.org/"
BUG_REPORT_URL="https://bugs.artixlinux.org/"
PRIVACY_POLICY_URL="https://terms.artixlinux.org/docs/privacy-policy/"
LOGO=artixlinux-logo


plugins:

```

</details>

### Description

Start hyprlock, power cycle monitor, full red screen.

Hyprlock goes off automatically via idle program (swayidle, because I can't get hypridle to work) while the monitor is off - turning the monitor back on, I see a red screen.  I think it breaks when you turn it back on, not before.

### How to reproduce

I can't imagine why it wouldn't be the same on any computer with an external monitor.

### Crash reports, logs, images, videos

Log from hyprlock -v:

[hyprlocklog.txt](https://github.com/user-attachments/files/16848890/hyprlocklog.txt)

**Comment by npc-z** [comment] 2024-09-03 13:49
I have the same problem.

Hyprlock version 0.4.1

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch main at commit 9a09eac79b85c846e3a865a9078a3f8ff65a9259  (props: bump version to 0.42.0).
Date: 2024-08-07
Tag: v0.42.0, commits: 9a09eac79b85c846e3a865a9078a3f8ff65a9259

flags: (if any)


System Information:
System name: Linux
Node name: ser7-nixos
Release: 6.10.6
Version: #1-NixOS SMP PREEMPT_DYNAMIC Mon Aug 19 04:05:40 UTC 2024


GPU information: 
c5:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Phoenix1 [1002:15bf] (rev c2) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.11.20240828.71e91c4"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.11 (Vicuna)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.11 (Vicuna)"
VERSION_CODENAME=vicuna
VERSION_ID="24.11"


plugins:
  hyprbars by Vaxry ver 1.0
  hyprscroller by dawser ver 1.0
```

</details>

**Comment by PaideiaDilemma** [comment] 2024-09-03 14:18
Can you please try hyprlock-git?

**Comment by PaideiaDilemma** [comment] 2024-09-03 14:45
Nevermind, this is a dupe of #434

You can try executing `hyprctl keyword monitor "FALLBACK,1920x1080@60,auto,1"` and i think that should fix it as well.

**Comment by PaideiaDilemma** [comment] 2024-09-03 15:15
Yeah this is not a hyprlock issue, but hl/aq. Fixed with hyprwm/aquamarine@16bbbcb.

> but hyprctl keyword monitor "FALLBACK,1920x1080@60,auto,1" works for me.

You can put `monitor=FALLBACK,1920x1080@60,auto,1` in your config for now until your aq version includes the commit mentioned above.

**Comment by djvs** [comment] 2024-09-03 18:15
Into what config?

**Comment by npc-z** [comment] 2024-09-04 01:04
> Yeah this is not a hyprlock issue, but hl/aq. Fixed with [hyprwm/aquamarine@16bbbcb](https://github.com/hyprwm/aquamarine/commit/16bbbcb).
> 
> > but hyprctl keyword monitor "FALLBACK,1920x1080@60,auto,1" works for me.
> 
> You can put `monitor=FALLBACK,1920x1080@60,auto,1` in your config for now until your aq version includes the commit mentioned above.

Thanks for your help! Ha, i put this in my hyprland config
```
exec-once = hyprctl keyword monitor "FALLBACK,1920x1080@60,auto,1"
```
so, i should put this alongside the other monitors config?
```
monitor=FALLBACK,1920x1080@60,auto,1
```

**Comment by PaideiaDilemma** [comment] 2024-10-01 16:57
Use latest aquamarine git, or put `monitor=FALLBACK,1920x1080@60,auto,1` along your other monitor configurations as a temporary fix.

I think this can be closed.

**Comment by PaideiaDilemma** [comment] 2024-11-02 15:45
Can be closed i think?

**Closed** 2024-11-02 23:41 UTC
Labels: bug
