### ISSUE TITLE
Placeholder text is visible when fade_on_empty = true

### ISSUE THREAD

**Issue by ZackMitkin** [hyprwm/hyprlock#51] opened 2024-02-21 18:38 UTC
I don't think it makes sense to show the placeholder for a split second when the input is fading out

Can be overcome by setting `placeholder_text = ""` in the config.

I think this can be fixed by defaulting `fade_on_empty = false` or `placeholder_text = ""` , or just don't show placeholder text when fade_on_empty is true

**Comment by davc0n** [comment] 2024-07-02 18:34
@vaxerski wdyt?

If `fade_on_empty = true`, should we disable `placeholder_text` and maybe also `fail_text`?

**Comment by vaxerski** [comment] 2024-07-03 10:52
no, we should just make it fade properly no?

**Comment by davc0n** [comment] 2024-07-03 13:23
The input box fades properly, imho the point is that with the default configuration happens this:

>I don't think it makes sense to show the placeholder for a split second when the input is fading out

Imho we could just change the default value of `placeholder_text` to an empty string to keep it unrelated from `fade_on_empty`.
Otherwise we could disable `placeholder_text` (and eventually the `fail_text`) when `fade_on_empty` is enabled.

Let me know if you agree with either one I will do a MR.

**Comment by PaideiaDilemma** [comment] 2024-07-03 14:43
Just to be on the same page, this is how the fade currently looks with default `fade_timeout`. It was adjusted in https://github.com/hyprwm/hyprlock/commit/6fa65e1172d633e61ed957a49e7cf96010432623. So if you are on a tagged release, it does not look the same.

https://github.com/hyprwm/hyprlock/assets/78690852/edb5d767-2873-4b7a-9d3a-3d8dd19ff044

> I don't think it makes sense to show the placeholder for a split second when the input is fading out

Since the commit I mentioned it shows for a second and I think it looks pretty ok.

I don't really know why you would want to set the default placeholder_text to an empty string. That looks worse for my taste.

I would get the argument that when you enter a wrong password, you might want to fade out, without having the placeholder show up before that. That currently works pretty well with `fade_timeout=800` (That is since the failure display lasts 1 second, which is not configurable yet. So if `fade_timeout` is below that, it fades out before the placeholder text renders again). Look like that.

https://github.com/hyprwm/hyprlock/assets/78690852/31684404-177c-41a1-8deb-12160381c770

**Comment by davc0n** [comment] 2024-07-03 15:53
>I don't really know why you would want to set the default placeholder_text to an empty string. That looks worse for my taste.

Not for my taste (and also @ZackMitkin which opened this issue). But well since there are different opinions let's keep the current behavior.

About the `fail_text`, imho it's hidden too early, I would increase the default timeout to 2 sec (equals the default `fade_timeout`) and make it configurable. I can try to make a MR for that if you agree.

**Comment by PaideiaDilemma** [comment] 2024-07-03 16:08
> About the fail_text, imho it's hidden too early, I would increase the default timeout to 2 sec (equals the default fade_timeout) and make it configurable. I can try to make a MR for that if you agree.

Ok I think I agree with you on that it could timeout a bit later. But having them equal does not work well, since the placeholder might render for a few frames before the timeout. I guess I would decrease the default `fade_timeout` a bit in that case, so that it is below the 2 secs.

I think it would be good to also make the timeout for the fail text configurable. Btw. the value is [here](https://github.com/hyprwm/hyprlock/blob/88b9ce48ed0c561c44c3a09cd6cef0e1bebaf59f/src/core/hyprlock.cpp#L778C1-L778C133).

**Comment by davc0n** [comment] 2024-07-07 08:53
I've added an option to make it configurable (ref. https://github.com/hyprwm/hyprlock/pull/406).

>But having them equal does not work well, since the placeholder might render for a few frames before the timeout. I guess I would decrease the default fade_timeout a bit in that case, so that it is below the 2 secs.

You're right, it seems that if `fail_timeout` is greater than `fade_timeout` the input disappears when `fail_timeout` is over but without fade effect.

**Comment by PaideiaDilemma** [comment] 2024-07-07 10:36
> if fail_timeout is greater than fade_timeout the input disappears when fail_timeout is over without fade effect.

Hmm I cannot reproduce that. When `fail_timeout` is bigger that `fade_timeout` it still fades on my end. Also see recording above

**Comment by davc0n** [comment] 2024-07-10 09:02
Correct, likely there was something dirty in my local build. I think we can close this.

**Comment by davc0n** [comment] 2024-07-13 12:16
@ZackMitkin @vaxerski can you close this?

**Closed** 2024-07-13 12:29 UTC
