### ISSUE TITLE
Background not applied if no label widget is present

### ISSUE THREAD

**Issue by v4u6h4n** [hyprwm/hyprlock#435] opened 2024-07-22 21:41 UTC
If there is no label widget present in the config, the background widget doesnt seem to be applied during lock.

**Comment by PaideiaDilemma** [comment] 2024-07-23 13:45
Works for me. Which hyprlock version are you on?

**Comment by AAGaming00** [comment] 2024-07-23 20:33
Running into the same issue on my freshly-updated NixOS system. hyprlock 0.4.0

**Comment by PaideiaDilemma** [comment] 2024-07-24 09:25
Sorry, need your hyprland version as well!

**Comment by v4u6h4n** [comment] 2024-07-24 19:58
@PaideiaDilemma 

Sorry for the delay, im on:

Hyprlock v0.4.0
Hyprland v0.41.2

**Comment by PaideiaDilemma** [comment] 2024-07-26 08:58
You are right, I can reproduce. But it is fixed in v0.4.1 (fixed by #421 i think).
So I would consider it as resolved.

**Closed** 2024-07-26 16:39 UTC
