### ISSUE TITLE
Still able to interact with firefox 

### ISSUE THREAD

**Issue by JassonCordones** [hyprwm/hyprlock#309] opened 2024-05-04 01:06 UTC
I left my mouse cursor over a paused youtube video in firefox and locked the screen and the cursor was still the pointy finger. I left clicked and the video started playing behind the lock screen. I can play/pause behind the lock screen.

Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460

Firefox 125.0.3 (64-bit)

_Originally posted by @JassonCordones in https://github.com/hyprwm/hyprlock/issues/308#issuecomment-2093924025_

**Comment by vaxerski** [comment] 2024-05-04 01:08
can you test on hyprland-git?

**Comment by JassonCordones** [comment] 2024-05-04 01:21
Yep still  happening 

> $ hyprctl version
> Hyprland, built from branch main at commit a3b4923c4218535878dcf68d27d8eca4ab3e0981  (input: ignore destroyed devices in static events).
> Date: Fri May 3 19:48:25 2024
> Tag: v0.39.1-140-ga3b4923c, commits: 4600
> 
> flags: (if any)

**Comment by vaxerski** [comment] 2024-05-04 19:48
I'll close this as a dupe of #308

**Closed by vaxerski** 2024-05-04 19:48 UTC
