### ISSUE TITLE
[Bug] Hyprlock after sometime auto unlock and can't be use anymore

### ISSUE THREAD

**Issue by RyuuyaS** [hyprwm/hyprlock#305] opened 2024-05-03 13:00 UTC
After some time (10 minutes or so), hyprlock auto unlock and when I try hyprlock again, it returns this.
```
[LOG] [core] dmabufFeedbackMainDevice
[LOG] output 52 make LG Display model 0x05FE
[LOG] output 52 name eDP-1
[LOG] output 52 description LG Display 0x05FE (eDP-1)
[LOG] output 52 done
[LOG] Running on Hyprland
[LOG] Locking session
[ERR] Pam module "hyprlock" not found! Falling back to "su"
[WARN] Extension: .png
[LOG] eglQueryDmaBufModifiersEXT found 8 mods
[LOG] bo chose modifier 0
[LOG] onLockFinished called. Seems we got yeeten. Is another lockscreen running?
[LOG] Got dma frame with size [Vector2D: x: 1920, y: 1080]
[LOG] PAM_PROMPT: Password:
```

hyprlock.conf
```
source = $HOME/.cache/wal/colors-hyprland

general {
    grace = 1
}

background {
    monitor =
	path = screenshot   # screenshot of your desktop
	# path = $HOME/.config/rofi/.current_wallpaper   # NOTE only png supported for now
    color = $color7

    # all these options are taken from hyprland, see https://wiki.hyprland.org/Configuring/Variables/#blur for explanations
    blur_size = 4
    blur_passes = 2 # 0 disables blurring
    noise = 0.0117
    contrast = 1.3000 # Vibrant!!!
    brightness = 0.8000
    vibrancy = 0.2100
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.33 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.15 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = $color1
    inner_color = $color0
    font_color = $color7
    fade_on_empty = true
    placeholder_text = <i>Password...</i> # Text rendered in the input box when it's empty.
    hide_input = false
    
    position = 0, 200
    halign = center
    valign = bottom
}

# Date
label {
    monitor =
    text = cmd[update:18000000] echo "<b> "$(date +'%A, %-d %B %Y')" </b>"
    color = $color5
    font_size = 34
    font_family = JetBrains Mono Nerd Font 10

    position = 0, -150
    halign = center
    valign = top
}

# Week
label {
    monitor =
    text = cmd[update:18000000] echo "<b> "$(date +'Week %U')" </b>"
    color = $color7
    font_size = 24
    font_family = JetBrains Mono Nerd Font 10

    position = 0, -250
    halign = center
    valign = top
}

# Time
label {
    monitor =
# text = cmd[update:1000] echo "<b><big> $(date +"%I:%M:%S %p") </big></b>" # AM/PM
text = cmd[update:1000] echo "<b><big> $(date +"%H:%M:%S") </big></b>" # 24H
    color = $color7
    font_size = 94
    font_family = JetBrains Mono Nerd Font 10

    position = 0, 0
    halign = center
    valign = center
}

label {
    monitor =
    text =    $USER
    color = $color7
    font_size = 18
    font_family = Inter Display Medium

    position = 0, 100
    halign = center
    valign = bottom
}

label {
    monitor =
    text = cmd[update:60000] echo "<b> "$(uptime -p)" </b>"
    color = $color12
    font_size = 24
    font_family = JetBrains Mono Nerd Font 10
    position = 0, 0
    halign = right
    valign = bottom
}

image {
    monitor =
    path = $HOME/.config/rofi/.current_wallpaper
    size = 230
    rounding = -1
    border_size = 4
    border_color = $color12
    rotate = 0
    reload_time = -1
    position = 0, 300
    halign = center
    valign = bottom
}
```

**Comment by RyuuyaS** [comment] 2024-05-03 13:07
#205 related to this maybe

**Comment by acheong08** [comment] 2024-05-03 23:11
I'm having a similar issue where Hyprlock doesn't actually lock properly and I can still open terminals, just can't switch workspaces.

It was working fine a while ago.

**Comment by RyuuyaS** [comment] 2024-05-04 01:11
@PaideiaDilemma Sorry but can you take a look at this? This bug is kinda bad.

**Comment by PaideiaDilemma** [comment] 2024-05-04 06:13
Which version are you on guys?

**Comment by RyuuyaS** [comment] 2024-05-04 06:21
I'm on latest git

**Comment by PaideiaDilemma** [comment] 2024-05-04 07:19
Hmm odd. Can you share which distro you are using, so I can check out the "su" pam configuration?

The logs look fine though.

**Comment by PaideiaDilemma** [comment] 2024-05-04 07:23
@acheong08 This is probably https://github.com/hyprwm/hyprlock/issues/308 

But `killall hyprlock` really should not crash the compositor. Instead it should leave you with the red screen of death.
Please try to reproduce this and check the Hyprland logs

**Comment by RyuuyaS** [comment] 2024-05-04 08:16
I'm using Fedora

**Comment by PaideiaDilemma** [comment] 2024-05-04 08:50
ok i will try to reproduce you issue later today :)

**Comment by RyuuyaS** [comment] 2024-05-05 10:47
Did you found something 😥

**Comment by RyuuyaS** [comment] 2024-05-05 12:26
I have tested the commit [eb1123f](https://github.com/hyprwm/hyprlock/commit/eb1123fa2ec5030448ac35280375d666d48f64de) which is before your commit, so the problem is not from your commit

**Comment by acheong08** [comment] 2024-05-05 17:32
Currently `git bisect`ing. Have been able to narrow it down quite a bit. Will update

**Comment by acheong08** [comment] 2024-05-05 17:54
```
90e1411315065ead5b5a7873be4109bdfb9f5470 is the first bad commit
commit 90e1411315065ead5b5a7873be4109bdfb9f5470
Author: Vaxry <vaxry@vaxry.net>
Date:   Tue Apr 30 16:32:05 2024 +0100

    session-lock: move to new impl
```

**Comment by acheong08** [comment] 2024-05-05 18:37
Since this is a Hyprland issue, we should close this and move discussion there

**Comment by RyuuyaS** [comment] 2024-05-06 05:37
I have updated to the latest git but it doesn't resolve the bug I'm facing, maybe your bug is different from mine. But I agree that it may be hyprland bug due to using swaylock resulting in the same bug.

**Comment by RyuuyaS** [comment] 2024-05-06 05:40
Hello @Mr-Ples, can you test if this problem happens with swaylock.

**Comment by vaxerski** [comment] 2024-05-07 10:44
move to https://github.com/hyprwm/Hyprland/issues/5913 please

**Closed by vaxerski** 2024-05-07 10:44 UTC
