### ISSUE TITLE
Crash when disconnecting a monitor

### ISSUE THREAD

**Issue by Ciflire** [hyprwm/hyprlock#196] opened 2024-03-15 20:47 UTC
I get a red screen if i try to unplug my secondary monitor while hyprlock is running

**Comment by fufexan** [comment] 2024-03-15 21:02
Duplicate of https://github.com/hyprwm/hyprlock/issues/65?

**Comment by erahhal** [comment] 2024-04-17 17:30
I'm seeing the same thing

**Closed** 2024-06-21 08:10 UTC
