### ISSUE TITLE
Unlocking after and automatic screen lock doesn't allow to click any window

### ISSUE THREAD

**Issue by msmafra** [hyprwm/hyprlock#483] opened 2024-09-09 15:26 UTC
### Regression?

No

### Hyprlock Info and Version

<Enter your hyprlock version here>
hyprlock --version
Unknown option: --version
Usage: hyprlock [options]

Options:
  -v, --verbose            - Enable verbose logging
  -q, --quiet              - Disable logging
  -c FILE, --config FILE   - Specify config file to use
  --display (display)      - Specify the Wayland display to connect to
  --immediate              - Lock immediately, ignoring any configured grace period
  --immediate-render       - Do not wait for resources before drawing the background
  -h, --help               - Show this help message

❯ doas dnf info hyprlock
Last metadata expiration check: 1:45:08 ago on Mon Sep  9 10:05:45 2024.
Installed Packages
Name         : hyprlock
Version      : 0.4.1
Release      : 1.fc40
Architecture : x86_64
Size         : 480 k
Source       : hyprlock-0.4.1-1.fc40.src.rpm
Repository   : @System
From repo    : copr:copr.fedorainfracloud.org:solopasha:hyprland
Summary      : Hyprland's GPU-accelerated screen locking utility
URL          : https://github.com/hyprwm/hyprlock
License      : BSD-3-Clause
Description  : Hyprland's GPU-accelerated screen locking utility.

<details> <summary>Hyprlock config</summary>
```sh
source = ~/.config/hypr/conf.d/colors.conf

general {
    # Needed to show icons that use more than one space
    # and are followed only by a spaces
    text_trim = false
}

background {
     monitor =
     path = ~/.config/hypr/hyprlock.png
     color = rgba(5, 0, 0, 1.0)
     blur_passes = 2
     blur_size = 3
     noise = 0.0117
     contrast = 0.8916
     brightness = 0.8172
     vibrancy = 0.1696
     vibrancy_darkness = 0.5
     no_fade_in = false
     hide_cursor = false
     grace = 5
     disable_loading_bar = false
     font_family = SpaceMono Nerd Font
 }

# Hours
label {
    monitor =
    text = cmd[update:1000] echo -n "<b><big>$(date +"%H")</big></b>"
    color = $clockh
    font_size = 120
    font_family = Geist Mono 10
    shadow_passes = 3
    shadow_size = 4

    position = 0, -25
    halign = center
    valign = top
}

# Minutes
label {
    monitor =
    text = cmd[update:1000] echo -n "<b><big>$(date +"%M")</big></b>"
    color = $clockm
    font_size = 120
    font_family = Geist Mono 10
    shadow_passes = 3
    shadow_size = 4

    # x+92, y+92
    position = 0, -155
    halign = center
    valign = top
}

# "Monday"
label {
    monitor =
    text = cmd[update:18000000] echo -n "<b><big>"$(date +'%A')"</big></b>"
    color = $white
    font_size = 22
    font_family = CaskaydiaCove Nerd Font 10

    position = 0, -365
    halign = center
    valign = top
}

# "2, May"
label {
    monitor =
    text = cmd[update:18000000] echo -n "<b>"$(date +'%d %b')"</b>"
    color = $white
    font_size = 18
    font_family = CaskaydiaCove Nerd Font 10

    position = 0, -395
    halign = center
    valign = top
}

input-field {
    monitor =
    size = 250, 40
    outline_thickness = 3

    dots_size = 0.26 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.64 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    dots_rouding = -1

    rounding = 15
    outer_color = $border
    inner_color = $backgd
    font_color = $foregd
    fade_on_empty = true
    placeholder_text = <b>Password...</b>
    position = 0, 60
    halign = center
    valign = bottom
}

#__medialock__ Media player info (this line toggles automatically)
#source = ~/.config/hypr/conf.d/medialock.conf

```

</details>

### Compositor Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 0f594732b063a90d44df8c5d402d658f27471dfe  (props: bump version to 0.43.0).
Date: Sun Sep 8 16:48:21 2024
Tag: v0.43.0, commits: 5196

flags: (if any)


System Information:
System name: Linux
Node name: fedora
Release: 6.10.9-cb1.0.fc40.x86_64
Version: #1 SMP PREEMPT_DYNAMIC Sun Sep  8 22:44:52 UTC 2024


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU106M [GeForce RTX 2060 Mobile] [10de:1f15] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX Open Kernel Module for x86_64  560.35.03  Release Build  (dvs-builder@U16-I1-N07-12-3)  Fri Aug 16 21:42:42 UTC 2024


os-release: NAME="Fedora Linux"
VERSION="40 (Workstation Edition)"
ID=fedora
VERSION_ID=40
VERSION_CODENAME=""
PLATFORM_ID="platform:f40"
PRETTY_NAME="Fedora Linux 40 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:40"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f40/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=40
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=40
SUPPORT_END=2025-05-13
VARIANT="Workstation Edition"
VARIANT_ID=workstation


plugins:
  hyprbars by Vaxry ver 1.0


```

</details>

### Description

When the screen locks up automatically, coming back from it doesn't allow interactions, like to click windows or change workspaces. To be able to use the system again I have to go to a tty, usually CTRL + F4, and get back to the the one used by Hyprland CTRL + F2.
Weirdly, Waybar, for some reason, still registers which workspace is active when I move the mouse between monitors, but seems nothing else works.

It's been happening for a while it seems, but as I usually don't let my machine autolock itself when I know I'll be away for several minutes. I did not notice it a lot before on previous versions, but was happening.

aquamarine-0.4.1-1.fc40.x86_64, hyprland-0.43.0-1.fc40.x86_64  

### How to reproduce

Let the system in idle to autolock/enter the screen lock.

Mind you, I'm on a Lenovo 5i laptop with a i7-10750h with a RTX 2060 mobile, using driver version 560.35.03.

### Crash reports, logs, images, videos

journalctl -b0 --user -u hypridle
-- No entries --

**Comment by PaideiaDilemma** [comment] 2024-09-09 15:47
This is a dupe of #459 i think.
Setting `general:no_fade_out` to true might fix it.

**Comment by msmafra** [comment] 2024-09-09 18:20
> This is a dupe of #459 i think. Setting `general:no_fade_out` to true might fix it.

It seems that it doesn't happen with no_fade_out = true. At least didn't happen last 3 times since I changed it.

**Closed** 2024-09-10 11:37 UTC
Labels: bug
