### ISSUE TITLE
Red screen only on wrong password

### ISSUE THREAD

**Issue by defr0std** [hyprwm/hyprlock#123] opened 2024-03-02 18:06 UTC
Hi,

Could you help me debug the following problem? If I type a correct password, everything works great. However, on a wrong password I am getting the red screen. Reproduces with or without any configuration file.

How could I see the output of the hyprlock in this case? I tried running `hyprlock &> ~/hyrlock.log`. When I enter the correct password, I am getting all the log, however for the wrong password the file is empty after restart.

Is there also a way to test this scenario without restarting computer each time the hyprlock crashes?

**Comment by liraz747** [comment] 2024-03-02 18:31
You can try to switch TTYs
You can activate hyprlock from a different tty to see the log like this - `WAYLAND_DISPLAY=wayland-1 hyprlock`
Then switch back to the tty where hyprland is active, do what causes the issue and then go back to the other tty

**Comment by defr0std** [comment] 2024-03-02 20:53
Hm, still empty file on another tty, and hyprlock is not running anymore. Looks like it's crashing before logging anything...

**Comment by liraz747** [comment] 2024-03-02 20:56
Try to run the command without outputting to a file, I had a similar issue of getting empty log files when doing that

See what gets outputted to the tty

**Comment by frigaut** [comment] 2024-03-03 03:51
It's not just you @defr0std, I am having the same issue.

**Comment by kulothunganug** [comment] 2024-03-03 08:47
I was also faced with the red screen issue twice, but I can't reproduce it...

**Comment by defr0std** [comment] 2024-03-03 16:43
> Try to run the command without outputting to a file, I had a similar issue of getting empty log files when doing that
> 
> See what gets outputted to the tty

Oh, thanks, I see. In that case I am hitting another issue - after I run the hyprlock on another tty, the wayland tty locks, but freezes. No labels or password input box appears, typing the password does nothing either. Need to solve this one first now.

**Comment by PaideiaDilemma** [comment] 2024-03-07 20:38
This has probably been fixed with #140

**Closed** 2024-03-08 02:09 UTC

**Comment by defr0std** [comment] 2024-03-10 13:50
Thanks! Works great now!
